data_dir: "data"
db_dir: "storage"
stocks_file: "./storage/stocks.csv"


push:
  enable: false
  url: "https://example.com:5378/api/send_message"
  admin: "admin@example.com"
  admin_pass: "password"
  user: "user@example.com"
